### ISSUE TITLE
Will it Delete the Local files after the Sync?

### ISSUE THREAD

**Issue by nenokkadine** [IntoMedia/rclone-sync#1]

**Comment by vmarci21** [comment]
If the file will delete in the remote cloud, yes the local file will be delete too. Any other cases the local files will be not deleted.

**Comment by nenokkadine** [comment]
> If the file will delete in the remote cloud, yes the local file will be delete too. Any other cases the local files will be not deleted.
Oh ok thanks Dude

**Comment by nenokkadine** [comment]
What if I Only Need to Only Sync Files to Cloud But it Should Never check its availability on My Local 
Like can i remove These Lines
`    def process_IN_OPEN(self, event):
        if not serverSync:
            run_lasts()
            loop = asyncio.new_event_loop()
            loop.run_until_complete(sync_form_cloud())
            loop.close()
`
`
   def process_IN_ACCESS(self, event):
        if not serverSync:
            if event.dir:
                run_lasts()
                loop = asyncio.new_event_loop()
                loop.run_until_complete(sync_form_cloud())
                loop.close()
`
and these
`    
def process_IN_DELETE(self, event):
        global lastRunning, clientSync
        if not serverSync:
            lastRunning = time.time()
            clientSync = True
            sync_delete(event.path, event.pathname)
            clientSync = False
`
in  main.py

**Comment by vmarci21** [comment]
Thanks your feedback! 
I will update the repository soon with this feature. :wink:

**Comment by nenokkadine** [comment]
> Thanks your feedback!
> I will update the repository soon with this feature. 😉

Thanks Dude

**Comment by vmarci21** [comment]
Now you can use this feature. After you downloaded the new py files, you can find more info by this command:
`./option.py help`

> Allowed sync types:
>  default	two-way sync
>    1    	local -> remote
>    2    	remote -> local

so if you want to set an sync from local to remote, you can use this command:
`./option.py local-dir remote-drive:/remote-dir 1`

**Comment by nenokkadine** [comment]
Nice Work Bro Keep Going😉
